(()=>{
const CHANNELS=[['national_retail','National Retail'],['regional_retail','Regional Retail'],['independent_retail','Independent Retail'],['convenience_travel','Convenience & Travel'],['12v','12V / Automotive Specialty'],['ci','CI / Custom Integration'],['mass','Mass Retail'],['ce','Consumer Electronics'],['ecommerce','E-commerce / Marketplace'],['distribution','Distribution'],['specialty_av','Specialty AV'],['office','Office'],['furniture','Furniture'],['club','Club / Warehouse'],['home_improvement','Home Improvement'],['automotive','Automotive'],['appliances','Appliances']];
const style=document.createElement('style');style.textContent=`
.channelMulti{position:relative;min-width:245px}.channelMulti>button{width:100%;min-height:40px;text-align:left;border:1px solid #d6e1ed;border-radius:10px;padding:9px 11px;background:#fff;color:#18324e;cursor:pointer}.channelMenu{display:none;position:absolute;z-index:25;top:calc(100% + 5px);left:0;width:330px;max-height:360px;overflow:auto;background:#fff;border:1px solid #d6e1ed;border-radius:12px;padding:10px;box-shadow:0 14px 38px rgba(18,49,85,.18)}.channelMulti.open .channelMenu{display:block}.channelMenu label{display:flex;align-items:center;gap:8px;padding:7px 5px;font-size:11px;font-weight:700}.channelMenu input{min-width:auto;width:16px;height:16px}.channelMenuActions{display:flex;gap:7px;position:sticky;top:-10px;background:#fff;padding:5px 0 8px}.selectedChannelChips{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px}.selectedChannelChips .badge{cursor:pointer}
#retailChannelsScreen{display:none}.channelManagerGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:14px}.channelManagerOption{display:flex;align-items:center;gap:9px;border:1px solid #dce7f2;border-radius:12px;padding:12px;background:#f9fbfe;font-size:11px;font-weight:800}.channelManagerOption input{width:17px;height:17px}.channelManagerActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}
@media(max-width:900px){.channelManagerGrid{grid-template-columns:1fr 1fr}}@media(max-width:760px){.channelMulti{width:100%}.channelMenu{position:relative;width:100%;top:5px}.channelManagerGrid{grid-template-columns:1fr}}
`;document.head.appendChild(style);
window.selectedAccountChannels=window.selectedAccountChannels||new Set();
window.accountChannelFilterHtml=function(){return `<div class="channelMulti" id="acctChannelMulti"><button type="button" onclick="toggleAccountChannelMenu(event)"><b>Channels:</b> <span id="acctChannelLabel">All channels</span> ▾</button><div class="channelMenu" onclick="event.stopPropagation()"><div class="channelMenuActions"><button class="btn ghost" type="button" onclick="setAllAccountChannels(true)">Select All</button><button class="btn secondary" type="button" onclick="setAllAccountChannels(false)">Clear</button></div>${CHANNELS.map(([code,label])=>`<label><input type="checkbox" class="acctChannelCheck" value="${code}" onchange="updateAccountChannelSelection()"> ${label}</label>`).join('')}</div><div class="selectedChannelChips" id="acctChannelChips"></div></div>`};
window.toggleAccountChannelMenu=function(event){event.stopPropagation();document.getElementById('acctChannelMulti')?.classList.toggle('open')};
window.updateAccountChannelSelection=function(){window.selectedAccountChannels=new Set([...document.querySelectorAll('.acctChannelCheck:checked,.channelManagerCheck:checked')].map(x=>x.value));const labels=CHANNELS.filter(([code])=>window.selectedAccountChannels.has(code)).map(([,label])=>label);document.querySelectorAll('.acctChannelCheck,.channelManagerCheck').forEach(x=>x.checked=window.selectedAccountChannels.has(x.value));const label=document.getElementById('acctChannelLabel'),chips=document.getElementById('acctChannelChips');if(label)label.textContent=labels.length?`${labels.length} selected`:'All channels';if(chips)chips.innerHTML=labels.map(text=>`<span class="badge">${text}</span>`).join('')};
window.setAllAccountChannels=function(checked){document.querySelectorAll('.acctChannelCheck,.channelManagerCheck').forEach(x=>x.checked=checked);updateAccountChannelSelection()};
document.addEventListener('click',()=>document.getElementById('acctChannelMulti')?.classList.remove('open'));

const originalAccounts=typeof window.accounts==='function'?window.accounts:null;
if(originalAccounts){
  window.accounts=function(){const html=originalAccounts();const single=/<select id="acctChannel">[\s\S]*?<\/select>/;return html.replace(single,accountChannelFilterHtml()).replace('<button id="retailerDiscoveryBtn"',`<button id="channelSyncBtn" class="btn secondary" onclick="syncExpandedChannelUniverse(this)">Sync Expanded Channels</button> <button id="retailerDiscoveryBtn"`)};
}
window.searchAccounts=async function(){try{const q=encodeURIComponent(document.getElementById('acctQ')?.value||''),channels=encodeURIComponent([...window.selectedAccountChannels].join(','));const d=await api(`/api/account-universe?q=${q}&channels=${channels}&limit=500`);const target=document.getElementById('accountResults');if(target)target.innerHTML=accountTable(d.organizations||[])}catch(e){toast(e.message)}};
window.syncExpandedChannelUniverse=async function(button){button=button||document.getElementById('channelSyncBtn')||document.getElementById('channelManagerSyncBtn');if(button){button.disabled=true;button.textContent='Syncing Channels…'}try{const d=await api('/api/channel-universe-sync',{method:'POST',body:'{}'});if(typeof load==='function')await load();if(typeof render==='function')render();toast(`${d.added} accounts added · ${d.updated} enriched across ${d.channels} channel groups`);ensureRetailChannelsTab()}catch(e){toast(e.message);if(button){button.disabled=false;button.textContent='Sync Expanded Channels'}}};
window.openRetailChannels=function(btn){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));const screen=document.getElementById('retailChannelsScreen');if(screen){screen.style.display='block';screen.classList.add('active')}document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');updateAccountChannelSelection()};
function ensureRetailChannelsTab(){
  const nav=document.querySelector('.nav');
  const content=document.querySelector('.content');
  if(nav&&!document.getElementById('retailChannelsNav')){
    const btn=document.createElement('button');btn.id='retailChannelsNav';btn.type='button';btn.textContent='Retail Channels';btn.onclick=function(){openRetailChannels(btn)};nav.appendChild(btn);
  }
  if(content&&!document.getElementById('retailChannelsScreen')){
    const screen=document.createElement('section');screen.id='retailChannelsScreen';screen.className='screen';screen.innerHTML=`<div class="pageHead"><div><div class="eyebrow">ACCOUNT UNIVERSE</div><h1>Retail Channels</h1><p>Manage the retailer channel universe, including Convenience & Travel, 12V / Automotive Specialty and CI / Custom Integration. Accounts can belong to multiple channels.</p></div><button id="channelManagerSyncBtn" class="btn" onclick="syncExpandedChannelUniverse(this)">Sync Expanded Channels</button></div><div class="card"><div class="label">Channel classifications</div><div class="channelManagerGrid">${CHANNELS.map(([code,label])=>`<label class="channelManagerOption"><input type="checkbox" class="channelManagerCheck" value="${code}" onchange="updateAccountChannelSelection()"> ${label}</label>`).join('')}</div><div class="channelManagerActions"><button class="btn ghost" onclick="setAllAccountChannels(true)">Select All</button><button class="btn secondary" onclick="setAllAccountChannels(false)">Clear</button><button class="btn dark" onclick="openAccountsForSelectedChannels()">View Matching Accounts</button></div></div>`;content.appendChild(screen);
  }
}
window.openAccountsForSelectedChannels=function(){const btn=[...document.querySelectorAll('.nav button')].find(b=>/accounts/i.test(b.textContent||''));if(btn)btn.click();setTimeout(()=>{document.querySelectorAll('.acctChannelCheck').forEach(x=>x.checked=window.selectedAccountChannels.has(x.value));updateAccountChannelSelection();if(typeof window.searchAccounts==='function')window.searchAccounts()},50)};
ensureRetailChannelsTab();
new MutationObserver(()=>ensureRetailChannelsTab()).observe(document.body,{childList:true,subtree:true});
})();
