(()=>{
 if(window.__L36_MULTI_USER__)return;window.__L36_MULTI_USER__=true;
 const css=document.createElement('style');css.textContent=`
 .l36-login{position:fixed;inset:0;z-index:1000;background:linear-gradient(135deg,#071a39,#0d3b73);display:grid;place-items:center;padding:20px}.l36-login-card{width:min(440px,94vw);background:white;border-radius:22px;padding:28px;box-shadow:0 28px 80px rgba(0,0,0,.3)}.l36-login-card h1{margin:0 0 6px;font-size:28px}.l36-login-card p{color:#71869e;font-size:12px}.l36-login-card input{width:100%;margin:6px 0 10px;border:1px solid #d6e1ed;border-radius:11px;padding:12px}.l36-workspace-btn{border:1px solid #d6e1ed;background:#fff;color:#17324f;border-radius:999px;padding:8px 12px;font-weight:800;cursor:pointer}.l36-admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.l36-admin-list{border:1px solid #dce7f2;border-radius:12px;padding:10px;max-height:300px;overflow:auto}.l36-user-row{display:flex;justify-content:space-between;gap:10px;padding:9px;border-bottom:1px solid #edf2f7}.l36-user-row:last-child{border-bottom:0}@media(max-width:760px){.l36-admin-grid{grid-template-columns:1fr}}`;
 document.head.appendChild(css);
 let profile=null;
 async function call(url,opt={}){const r=await fetch(url,{headers:{'content-type':'application/json',...(opt.headers||{})},credentials:'same-origin',...opt});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||`Request failed (${r.status})`);return b}
 function loginOverlay(){if(document.getElementById('l36Login'))return;const el=document.createElement('div');el.id='l36Login';el.className='l36-login';el.innerHTML=`<div class="l36-login-card"><div class="eyebrow">LAUNCHPAD36 AI</div><h1>Sign in</h1><p>Use the login created for your Launchpad36 workspace.</p><input id="l36Email" type="email" placeholder="Email"><input id="l36Password" type="password" placeholder="Password"><input id="l36Workspace" placeholder="Workspace name (only if prompted)"><button class="btn" style="width:100%" id="l36LoginBtn">Sign in</button><div id="l36LoginMsg" class="muted" style="margin-top:10px"></div></div>`;document.body.appendChild(el);document.getElementById('l36LoginBtn').onclick=async()=>{const btn=document.getElementById('l36LoginBtn');btn.disabled=true;document.getElementById('l36LoginMsg').textContent='Signing in…';try{await call('/api/auth-login',{method:'POST',body:JSON.stringify({email:document.getElementById('l36Email').value,password:document.getElementById('l36Password').value,workspace:document.getElementById('l36Workspace').value})});location.reload()}catch(e){document.getElementById('l36LoginMsg').textContent=e.message;btn.disabled=false}}}
 function addWorkspaceButton(){if(document.getElementById('l36WorkspaceBtn'))return;const top=document.querySelector('.top');if(!top)return;const btn=document.createElement('button');btn.id='l36WorkspaceBtn';btn.className='l36-workspace-btn';btn.textContent=profile?.user?.display_name||profile?.user?.email||'Workspace';btn.onclick=openWorkspace;top.appendChild(btn)}
 async function openWorkspace(){
  let body=`<div class="pageHead"><div><div class="eyebrow">WORKSPACE</div><h1>${esc(profile?.user?.manufacturer_name||'Launchpad36')}</h1><p>${esc(profile?.user?.display_name||profile?.user?.email||'')} · ${esc(profile?.user?.role||'')}</p></div><button class="btn ghost" onclick="l36Logout()">Sign out</button></div>`;
  const admin=['owner','admin'].includes(String(profile?.user?.role||'').toLowerCase())||!profile?.user?.id;
  if(admin){try{const d=await call('/api/team-admin');body+=`<div class="l36-admin-grid"><div class="card"><h3>Users</h3><div class="l36-admin-list">${d.members.map(m=>`<div class="l36-user-row"><div><b>${esc(m.display_name||m.email)}</b><div class="muted">${esc(m.email)} · ${esc(m.role)}</div></div><span class="pill">${m.active?'Active':'Inactive'}</span></div>`).join('')||'<div class="empty">No users yet</div>'}</div><h3 style="margin-top:18px">Create user</h3><div class="formGrid"><div class="field"><label>Name</label><input id="wuName"></div><div class="field"><label>Email</label><input id="wuEmail"></div><div class="field"><label>Password</label><input id="wuPass" type="password"></div><div class="field"><label>Role</label><select id="wuRole"><option>member</option><option>manager</option><option>viewer</option><option>admin</option></select></div><div class="field full"><label>Team</label><select id="wuTeam"><option value="">Private product scope</option>${d.teams.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('')}</select></div></div><button class="btn" style="margin-top:10px" onclick="l36CreateUser()">Create user</button></div><div class="card"><h3>Groups / Teams</h3><div class="l36-admin-list">${d.teams.map(t=>`<div class="l36-user-row"><div><b>${esc(t.name)}</b><div class="muted">${esc(t.description||'Shared product group')}</div></div><span class="pill">${t.active?'Active':''}</span></div>`).join('')||'<div class="empty">No teams yet</div>'}</div><h3 style="margin-top:18px">Create team</h3><div class="field"><label>Team name</label><input id="wtName"></div><div class="field"><label>Description</label><input id="wtDesc"></div><button class="btn" style="margin-top:10px" onclick="l36CreateTeam()">Create team</button><div class="callout" style="margin-top:16px"><b>Product privacy</b><p class="muted">New member products are private by default. Assign a team to share product data within that group. Owners/admins can manage the full workspace.</p></div></div></div>`}catch(e){body+=`<div class="warning">${esc(e.message)}</div>`}}
  else body+=`<div class="card"><h3>Your access</h3><p class="muted">Teams: ${(profile.teams||[]).map(t=>esc(t.name)).join(', ')||'None'}. Product data you create is private unless assigned to one of your teams.</p></div>`;
  if(typeof modal==='function')modal('Workspace & Users',body);else{const host=document.createElement('div');host.innerHTML=body;document.body.appendChild(host)}
 }
 window.l36Logout=async()=>{await call('/api/auth-session',{method:'DELETE'});location.reload()};
 window.l36CreateTeam=async()=>{try{await call('/api/team-admin',{method:'POST',body:JSON.stringify({action:'create_team',name:document.getElementById('wtName').value,description:document.getElementById('wtDesc').value})});toast('Team created');openWorkspace()}catch(e){toast(e.message)}};
 window.l36CreateUser=async()=>{try{await call('/api/team-admin',{method:'POST',body:JSON.stringify({action:'create_user',display_name:document.getElementById('wuName').value,email:document.getElementById('wuEmail').value,password:document.getElementById('wuPass').value,role:document.getElementById('wuRole').value,team_id:document.getElementById('wuTeam').value})});toast('User created');openWorkspace()}catch(e){toast(e.message)}};
 (async()=>{try{profile=await call('/api/auth-session');window.__L36_PROFILE__=profile;addWorkspaceButton()}catch{loginOverlay()}})();
})();
