import crypto from 'crypto';
const clean=(v,m=1000)=>String(v??'').trim().slice(0,m);
function key(){const s=process.env.ADMIN_SECRET||process.env.CRM_ENCRYPTION_SECRET||'';if(!s)throw new Error('CRM encryption secret is not configured');return crypto.createHash('sha256').update(s).digest()}
export function encryptSecret(value=''){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key(),iv),enc=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]),tag=cipher.getAuthTag();return [iv,tag,enc].map(x=>x.toString('base64url')).join('.')}
export function decryptSecret(value=''){const [iv,tag,enc]=String(value).split('.').map(x=>Buffer.from(x,'base64url'));const decipher=crypto.createDecipheriv('aes-256-gcm',key(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(enc),decipher.final()]).toString('utf8')}
export async function hubspot(token,path,{method='GET',body}={}){const r=await fetch(`https://api.hubapi.com${path}`,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});let data={};try{data=await r.json()}catch{}if(!r.ok){const e=new Error(data.message||`HubSpot HTTP ${r.status}`);e.status=r.status;throw e}return data}
export async function findHubSpotObject(token,type,property,value){if(!value)return null;const d=await hubspot(token,`/crm/v3/objects/${type}/search`,{method:'POST',body:{filterGroups:[{filters:[{propertyName:property,operator:'EQ',value:String(value)}]}],limit:1}});return d.results?.[0]||null}
export async function upsertHubSpotObject(token,type,id,properties){if(id)return await hubspot(token,`/crm/v3/objects/${type}/${id}`,{method:'PATCH',body:{properties}});return await hubspot(token,`/crm/v3/objects/${type}`,{method:'POST',body:{properties}})}
export async function associateHubSpot(token,fromType,fromId,toType,toId){if(!fromId||!toId)return;await hubspot(token,`/crm/v4/objects/${fromType}/${fromId}/associations/default/${toType}/${toId}`,{method:'PUT'})}
export function opportunityCrmPayload(row){const s=row.scenario||{},buyer=s.assigned_buyer||(row.buyers||[])[0]||{},assortment=s.proposed_assortment||s.account?.product_contributions||[],amount=Number(s.account?.base_manufacturer_revenue)||0,parts=clean(buyer.name,180).split(/\s+/);return {company:{name:clean(row.account_name||s.account?.name,220),domain:clean(row.domain||s.account?.domain,240)},contact:{firstname:parts[0]||'',lastname:parts.slice(1).join(' '),email:clean(buyer.email,240),phone:clean(buyer.phone,80),jobtitle:clean(buyer.title||buyer.category,180)},deal:{dealname:`${clean(row.account_name||s.account?.name,180)} - Launchpad36 Opportunity`,amount:String(amount),description:clean(`L36 Opportunity ${row.id}. Route: ${row.route_to_market||''}. Status: ${row.status||''}. Owner: ${row.owner||''}. Next action: ${row.next_action||''}. Proposed SKUs: ${assortment.map(x=>[x.brand_name,x.product_name,x.sku].filter(Boolean).join(' ')).join('; ')}`,5000)},meta:{opportunity_id:String(row.id),route_to_market:row.route_to_market||'',status:row.status||'',owner:row.owner||'',next_action:row.next_action||'',fit_score:Number(s.account?.fit_score)||0,evidence_status:s.account?.evidence_status||'',amount,skus:assortment.map(x=>({brand:x.brand_name||'',product:x.product_name||'',sku:x.sku||'',in_store:Boolean(s.comparison_status?.[`${x.product_id}::${x.sku||''}`]?.in_store),online:Boolean(s.comparison_status?.[`${x.product_id}::${x.sku||''}`]?.online)}))}}
