import { requireInternal } from './_auth.js';

const BRANDS=['Sony','Samsung','LG','Bose','Sonos','JBL','Klipsch','KEF','Polk Audio','Bowers & Wilkins','Yamaha','Denon','Marantz','SVS','Audioengine','Sennheiser','Marshall','Vizio','Sanus','Rocketfish','Chief','Kanto','Ergotron','Humanscale','FlexiSpot','Vari','UPLIFT','Branch'];
function safeDomain(x){const d=String(x||'').toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').split('/')[0];return /^[a-z0-9.-]+\.[a-z]{2,}$/i.test(d)?d:''}
async function page(u){const c=new AbortController(),t=setTimeout(()=>c.abort(),6500);try{const r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0 Launchpad36AI/1.0'},redirect:'follow',signal:c.signal});if(!r.ok||!(r.headers.get('content-type')||'').includes('text/html'))return null;return {url:r.url,html:(await r.text()).slice(0,900000)}}catch{return null}finally{clearTimeout(t)}}
function txt(h=''){return h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()}
function same(u,d){try{const h=new URL(u).hostname.replace(/^www\./,'').toLowerCase();return h===d||h.endsWith('.'+d)}catch{return false}}
function pnum(s=''){const m=String(s).match(/\$?\s*([\d,]+(?:\.\d{2})?)/);return m?Number(m[1].replace(/,/g,'')):0}
function clamp(n){return Math.max(0,Math.min(100,n))}
function feats(s=''){const a=['wireless','bluetooth','wifi','premium','compact','portable','soundbar','speaker','subwoofer','mount','desk','standing','motorized','adjustable','ergonomic','audio','video','home theater','smart','app','voice','dolby','atmos','hdmi','earc','multiroom','active','powered'];s=String(s).toLowerCase();return a.filter(x=>s.includes(x))}
export default async function handler(req,res){
 if(!requireInternal(req,res)) return;
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
 const {domain:rd,account,products=[]}=req.body||{},d=safeDomain(rd);
 if(!d)return res.status(400).json({error:'Valid retailer domain required'});
 if(!Array.isArray(products)||!products.length)return res.status(400).json({error:'Manufacturer product/SKU data required'});
 const cat=(products.find(p=>p.category)?.category||'audio').toLowerCase(), q=encodeURIComponent(cat);
 const seeds=[`https://${d}/search?q=${q}`,`https://www.${d}/search?q=${q}`,`https://${d}/audio`,`https://${d}/electronics`,`https://${d}/tv-home-theater`,`https://${d}/office`,`https://${d}/furniture`];
 const pages=[]; for(const u of seeds){if(pages.length>=6)break;const p=await page(u);if(p&&same(p.url,d)&&!pages.some(x=>x.url===p.url))pages.push(p)}
 const competitors=[],seen=new Set();
 for(const p of pages){const t=txt(p.html),l=t.toLowerCase();for(const brand of BRANDS){const i=l.indexOf(brand.toLowerCase());if(i<0||seen.has(brand.toLowerCase()))continue;seen.add(brand.toLowerCase());const sn=t.slice(Math.max(0,i-180),Math.min(t.length,i+360)),pr=(sn.match(/\$\s?\d{1,5}(?:,\d{3})*(?:\.\d{2})?/g)||[])[0]||'';competitors.push({brand,product:sn.slice(0,220),price:pr,price_num:pnum(pr),features:feats(sn),source_url:p.url});if(competitors.length>=35)break}if(competitors.length>=35)break}
 const comps=[];let best=null,bscore=-1;
 for(const p of products){const of=Array.isArray(p.features)?p.features:[];let lb=0;for(const c of competitors.slice(0,20)){const ps=c.price_num?clamp(100-(Math.abs((Number(p.msrp)||0)-c.price_num)/Math.max(c.price_num,1))*100):55;const overlap=of.filter(f=>c.features.includes(f)).length,diff=clamp(70+(of.length-overlap)*7-overlap*3),opp=clamp(Math.round(ps*.45+diff*.55));lb=Math.max(lb,opp);comps.push({our_product:p.product,our_variant:p.variant,our_msrp:p.msrp,competitor_brand:c.brand,competitor_product:c.product,competitor_price:c.price,gap_summary:diff>=75?'Strong feature/positioning differentiation':ps>=75?'Close price comparison; differentiation required':'Distinct price position',opportunity_score:opp,source_url:c.source_url})}if(lb>bscore){bscore=lb;best={...p,score:lb}}}
 const our=products.map(p=>Number(p.msrp)||0).filter(Boolean),cp=competitors.map(c=>c.price_num).filter(Boolean),minO=Math.min(...our),maxO=Math.max(...our),minC=cp.length?Math.min(...cp):0,maxC=cp.length?Math.max(...cp):0;
 const density=clamp(100-Math.min(competitors.length*3,85)),priceGap=cp.length?clamp(Math.round(((minO<minC?minC-minO:0)+(maxO>maxC?maxO-maxC:0))/Math.max(maxC||1,1)*100)+55):70,fs=comps.map(c=>c.opportunity_score),featureGap=fs.length?Math.round(fs.reduce((a,b)=>a+b,0)/fs.length):65,overall=clamp(Math.round(priceGap*.35+featureGap*.45+density*.2));
 const white=[];if(cp.length&&minO<minC)white.push({title:'Entry-price white space',detail:'Your assortment reaches below the lowest competitor price detected.'});if(cp.length&&maxO>maxC)white.push({title:'Premium white space',detail:'Your portfolio extends above the highest detected competitive price.'});if(density>60)white.push({title:'Low competitive density',detail:'Relatively few directly overlapping brands were detected.'});if(featureGap>72)white.push({title:'Feature differentiation opportunity',detail:'Your SKU positioning shows meaningful differentiation.'});if(!white.length)white.push({title:'Execution-led opportunity',detail:'Price bands are crowded; winning depends on features, margin, merchandising and buyer-specific positioning.'});
 res.setHeader('Cache-Control','public, max-age=900, stale-while-revalidate=43200');
 res.status(200).json({account,overall_gap_score:overall,metrics:{price_gap:priceGap,feature_gap:featureGap,competitive_density:density},recommended_lead_sku:best?{product:best.product,variant:best.variant,msrp:best.msrp,reason:`Highest modeled opportunity score (${best.score}/100) against detected assortment.`}:null,white_spaces:white,comparisons:comps.sort((a,b)=>b.opportunity_score-a.opportunity_score),checked_pages:pages.map(p=>p.url),competitor_count:competitors.length});
}
