import { db } from './_db.js';
import { resolveTenant,canSeeAllTenantData } from './_tenant.js';
import { ensureIdentitySchema } from './_identity.js';

const clean=(value,max=1000)=>String(value??'').trim().slice(0,max),allowedVisibility=new Set(['private','team','tenant']);
function canEdit(row,tenant){return canSeeAllTenantData(tenant)||String(row.owner_user_id||'')===String(tenant.user_id||'')||(row.visibility==='team'&&(tenant.team_ids||[]).includes(String(row.team_id||'')))}
function scopeFor(input,tenant){
 const requested=allowedVisibility.has(String(input.visibility||'').toLowerCase())?String(input.visibility).toLowerCase():'';
 if(canSeeAllTenantData(tenant)){const visibility=requested||'private',teamId=visibility==='team'?clean(input.team_id,80)||null:null;if(visibility==='team'&&!teamId)throw Object.assign(new Error('Choose a team for this brand'),{status:400});return {visibility,team_id:teamId,owner_user_id:visibility==='private'?tenant.user_id:null}}
 const teamId=clean(input.team_id,80)||null;if(requested==='team'||teamId){if(!teamId||!(tenant.team_ids||[]).includes(teamId))throw Object.assign(new Error('You are not a member of that team'),{status:403});return {visibility:'team',team_id:teamId,owner_user_id:null}}
 return {visibility:'private',team_id:null,owner_user_id:tenant.user_id};
}
export async function accessibleBrand(sql,id,tenant){if(!id)return null;const row=(await sql`select * from brands where id=${id} and manufacturer_id=${tenant.tenant_id} and active=true limit 1`)[0];return row&&canEdit(row,tenant)?row:null}

export default async function handler(req,res){const tenant=await resolveTenant(req,res);if(!tenant)return;const sql=db();try{
 await ensureIdentitySchema(sql);const teamIds=tenant.team_ids||[],admin=canSeeAllTenantData(tenant);
 if(req.method==='GET'){const rows=admin?await sql`select * from brands where manufacturer_id=${tenant.tenant_id} and active=true order by name`:await sql`select * from brands where manufacturer_id=${tenant.tenant_id} and active=true and (owner_user_id=${tenant.user_id} or (visibility='team' and team_id=any(${teamIds}::uuid[])) or (visibility='tenant' and owner_user_id is null and team_id is null)) order by name`;return res.status(200).json({brands:rows})}
 if(req.method==='POST'){const body=req.body||{},name=clean(body.name,220);if(!name)return res.status(400).json({error:'brand name is required'});const scope=scopeFor(body,tenant);if(scope.team_id&&!(await sql`select id from manufacturer_teams where id=${scope.team_id} and manufacturer_id=${tenant.tenant_id} and active=true limit 1`)[0])return res.status(400).json({error:'Team is not part of this workspace'});const row=(await sql`insert into brands(manufacturer_id,name,website,logo_url,description,active,owner_user_id,team_id,visibility,updated_at) values(${tenant.tenant_id},${name},${clean(body.website)},${clean(body.logo_url)},${clean(body.description,3000)},true,${scope.owner_user_id},${scope.team_id},${scope.visibility},now()) returning *`)[0];return res.status(200).json({brand:row})}
 if(req.method==='PATCH'){const body=req.body||{},id=clean(body.id,80),name=clean(body.name,220);if(!id||!name)return res.status(400).json({error:'brand id and name are required'});const existing=(await sql`select * from brands where id=${id} and manufacturer_id=${tenant.tenant_id} and active=true limit 1`)[0];if(!existing)return res.status(404).json({error:'Brand not found'});if(!canEdit(existing,tenant))return res.status(403).json({error:'You do not have access to edit this brand'});const scope=scopeFor({...body,visibility:body.visibility||existing.visibility,team_id:body.team_id||existing.team_id},tenant);if(scope.team_id&&!(await sql`select id from manufacturer_teams where id=${scope.team_id} and manufacturer_id=${tenant.tenant_id} and active=true limit 1`)[0])return res.status(400).json({error:'Team is not part of this workspace'});const row=(await sql`update brands set name=${name},website=${clean(body.website)},logo_url=${clean(body.logo_url)},description=${clean(body.description,3000)},owner_user_id=${scope.owner_user_id},team_id=${scope.team_id},visibility=${scope.visibility},updated_at=now() where id=${id} and manufacturer_id=${tenant.tenant_id} returning *`)[0];return res.status(200).json({brand:row})}
 if(req.method==='DELETE'){const id=clean(req.query?.id||req.body?.id,80);if(!id)return res.status(400).json({error:'brand id is required'});const existing=(await sql`select * from brands where id=${id} and manufacturer_id=${tenant.tenant_id} and active=true limit 1`)[0];if(!existing)return res.status(404).json({error:'Brand not found'});if(!canEdit(existing,tenant))return res.status(403).json({error:'You do not have access to delete this brand'});const activeProducts=Number((await sql`select count(*)::int count from products where brand_id=${id} and manufacturer_id=${tenant.tenant_id} and active=true`)[0]?.count)||0;if(activeProducts)return res.status(409).json({error:`Delete or reassign ${activeProducts} active product(s) before deleting this brand`});await sql`update brands set active=false,updated_at=now() where id=${id}`;return res.status(200).json({deleted:true,brand:{id,name:existing.name}})}
 return res.status(405).json({error:'Method not allowed'});
}catch(error){console.error('brand operation failed',{message:error?.message||String(error)});const duplicate=error?.code==='23505';return res.status(error.status||(duplicate?409:500)).json({error:duplicate?'A brand with that name already exists':error.message||'Brand operation could not be completed'})}}
