import { db } from './_db.js';
import { resolveTenant } from './_tenant.js';
function text(v){return String(v??'').trim()}
function num(v){const n=Number(String(v??'').replace(/[$,]/g,''));return Number.isFinite(n)?n:0}
function split(v){return text(v).split(/[|;,]/).map(x=>x.trim()).filter(Boolean)}
export default async function handler(req,res){const t=await resolveTenant(req,res);if(!t)return;if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const rows=Array.isArray(req.body?.rows)?req.body.rows:[];if(!rows.length)return res.status(400).json({error:'rows are required'});const sql=db();const errors=[];let imported=0;const run=(await sql`insert into catalog_import_runs(manufacturer_id,source_type,source_name,rows_seen,status) values(${t.tenant_id},${req.body?.source_type||'excel'},${req.body?.source_name||''},${rows.length},'started') returning *`)[0];
 try{for(let i=0;i<rows.length;i++){const r=rows[i]||{};const brandName=text(r.brand||r.Brand);const productName=text(r.product_name||r.Product||r['Product Name']);const sku=text(r.sku||r.SKU||r['Model Number']);if(!brandName||!productName||!sku){errors.push({row:i+2,error:'Brand, Product Name and SKU are required'});continue}
  const brand=(await sql`insert into brands(manufacturer_id,name,website,active,updated_at) values(${t.tenant_id},${brandName},${text(r.brand_website||r['Brand Website'])},true,now()) on conflict(manufacturer_id,name) do update set active=true,updated_at=now() returning *`)[0];
  let product=(await sql`select * from products where manufacturer_id=${t.tenant_id} and brand_id=${brand.id} and lower(name)=lower(${productName}) limit 1`)[0];
  if(!product)product=(await sql`insert into products(manufacturer_id,brand_id,name,product_family,category,description,product_url,image_url,positioning,differentiator,source_type,source_url,active,updated_at) values(${t.tenant_id},${brand.id},${productName},${text(r.product_family||r['Product Family'])},${text(r.category||r.Category)},${text(r.description||r.Description)},${text(r.product_url||r['Product URL'])},${text(r.image_url||r['Image URL'])},${text(r.positioning||r.Positioning)},${text(r.differentiator||r.Differentiator)},${req.body?.source_type||'excel'},${text(r.source_url||r['Source URL']||r.product_url||r['Product URL'])},true,now()) returning *`)[0];
  await sql`insert into product_variants(product_id,sku,variant_name,msrp,map,wholesale,upc,model_number,image_url,product_url,attributes,active,updated_at) values(${product.id},${sku},${text(r.variant_name||r.Variant||r['Variant Name'])},${num(r.msrp||r.MSRP)},${num(r.map||r.MAP)},${num(r.wholesale||r.Wholesale)},${text(r.upc||r.UPC)},${text(r.model_number||r['Model Number'])},${text(r.image_url||r['Image URL'])},${text(r.product_url||r['Product URL'])},${sql.json({features:split(r.features||r.Features),source:'catalog_import'})},true,now()) on conflict(product_id,sku,variant_name) do update set msrp=excluded.msrp,map=excluded.map,wholesale=excluded.wholesale,upc=excluded.upc,model_number=excluded.model_number,image_url=excluded.image_url,product_url=excluded.product_url,attributes=excluded.attributes,active=true,updated_at=now()`;
  const cats=[...new Set([text(r.category||r.Category),...split(r.additional_categories||r['Additional Categories'])].filter(Boolean))];for(const c of cats)await sql`insert into product_categories(product_id,category) values(${product.id},${c}) on conflict do nothing`;
  for(const code of split(r.channels||r.Channels).map(x=>x.toLowerCase().replace(/[^a-z0-9]+/g,'_'))){const c=(await sql`select id from channels where code=${code} limit 1`)[0];if(c)await sql`insert into product_channels(product_id,channel_id) values(${product.id},${c.id}) on conflict do nothing`}
  imported++;
 }
 await sql`update catalog_import_runs set rows_imported=${imported},rows_rejected=${errors.length},status='complete',errors=${sql.json(errors)},finished_at=now() where id=${run.id}`;
 return res.status(200).json({version:'9.8',rows_seen:rows.length,rows_imported:imported,rows_rejected:errors.length,errors:errors.slice(0,50),interpretation:errors.length?'Import completed with review items.':'Catalog imported successfully.'});
 }catch(e){await sql`update catalog_import_runs set status='error',errors=${sql.json([{error:e.message}])},finished_at=now() where id=${run.id}`;return res.status(500).json({error:e.message})}}
