import { requireInternal } from './_auth.js';
const TITLES=['buyer','merchant','category manager','category director','merchandising','merchandise manager','director of merchandising','vice president merchandising','vp merchandising','general merchandise manager','divisional merchandise manager','category lead'];
const EMAIL=/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/ig, PHONE=/(?:\+?1[\s.-]?)?(?:\(?\d{3}\)?[\s.-]?)\d{3}[\s.-]\d{4}/g;
function text(h=''){return h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()}
function domain(v){const d=String(v||'').toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').split('/')[0];return /^[a-z0-9.-]+\.[a-z]{2,}$/i.test(d)?d:''}
async function page(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),6000);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 Launchpad36AI/1.0'},redirect:'follow',signal:c.signal});if(!r.ok||!(r.headers.get('content-type')||'').includes('text/html'))return null;return{url:r.url,html:(await r.text()).slice(0,500000)}}catch{return null}finally{clearTimeout(t)}}
function nameGuess(s,title){const i=s.toLowerCase().indexOf(title),raw=(i>=0?s.slice(Math.max(0,i-100),i):s.slice(0,100));const m=raw.match(/([A-Z][a-z]+(?:\s+[A-Z][a-z.'-]+){1,2})/g);return m?m[m.length-1]:''}
export default async function handler(req,res){
 if(!requireInternal(req,res)) return;if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const d=domain(req.query.domain),account=String(req.query.account||d);if(!d)return res.status(400).json({error:'Valid account domain required'});const seeds=['/about','/about-us','/leadership','/team','/management','/contact'];const fetched=await Promise.all(seeds.map(async p=>await page('https://'+d+p)||await page('https://www.'+d+p))),pages=[];for(const x of fetched)if(x&&!pages.some(y=>y.url===x.url))pages.push(x);const people=[],seen=new Set();for(const p of pages){const t=text(p.html),lo=t.toLowerCase(),emails=t.match(EMAIL)||[],phones=t.match(PHONE)||[];for(const title of TITLES){let at=lo.indexOf(title);while(at>=0&&people.length<12){const sn=t.slice(Math.max(0,at-180),Math.min(t.length,at+260)),n=nameGuess(sn,title);if(!n){at=lo.indexOf(title,at+title.length);continue}const key=(n+'|'+title+'|'+p.url).toLowerCase();if(!seen.has(key)){seen.add(key);people.push({name:n,title:title.replace(/\b\w/g,c=>c.toUpperCase()),organization:account,email:emails.find(e=>sn.includes(e))||'',phone:phones.find(ph=>sn.includes(ph))||'',source_url:p.url,source_label:'Public corporate website',confidence:78,verified_at:new Date().toISOString().slice(0,10),verification_status:'REVIEW_REQUIRED',contact_basis:'exactly displayed on the cited public page; no private contact inference'})}at=lo.indexOf(title,at+title.length)}}}res.setHeader('Cache-Control','public, max-age=900, stale-while-revalidate=86400');return res.status(200).json({people,checked_pages:pages.map(p=>p.url),method:'public-corporate-source',linkedin_policy:{mode:'verification_enrichment_only',bulk_scraping:false,private_contact_inference:false}})}
