import { resolveTenant } from './_tenant.js';

export const AURELIUS_AUDIO_DEMO=[
 {brand:'Aurelius Audio',product_name:'Lyra Mini Wireless Speaker',sku:'AUR-LYRA-M1',model_number:'AA-LM100-GR',product_family:'Lyra Personal Audio',category:'Portable Bluetooth Speakers',description:'Compact aluminum wireless speaker tuned for balanced near-field listening.',features:['Bluetooth 5.3','12-hour battery','USB-C audio','IPX5 splash resistance'],channels:['ecommerce','ce','department'],msrp:49.99,map:49.99,wholesale:25,image_url:'/assets/aurelius/lyra-mini.svg',additional_categories:['Personal Audio']},
 {brand:'Aurelius Audio',product_name:'Orion Pocket DAC',sku:'AUR-ORION-D1',model_number:'AA-OD120-SV',product_family:'Orion Digital',category:'Headphone Amplifiers',description:'Pocket USB-C DAC and headphone amplifier for lossless mobile listening.',features:['32-bit/384kHz PCM','DSD256','3.5mm output','Machined aluminum chassis'],channels:['ecommerce','specialty_av','ce'],msrp:79.99,map:69.99,wholesale:40,image_url:'/assets/aurelius/orion-dac.svg',additional_categories:['Digital Audio']},
 {brand:'Aurelius Audio',product_name:'Vesper True Wireless Earbuds',sku:'AUR-VESPER-E2',model_number:'AA-VE220-BK',product_family:'Vesper Personal Audio',category:'True Wireless Earbuds',description:'Premium compact earbuds with adaptive noise control and a low-profile charging case.',features:['Adaptive ANC','Multipoint Bluetooth','Six microphones','30-hour total battery'],channels:['ecommerce','ce','department'],msrp:129.99,map:119.99,wholesale:65,image_url:'/assets/aurelius/vesper-earbuds.svg',additional_categories:['Headphones']},
 {brand:'Aurelius Audio',product_name:'Cadenza Smart Speaker',sku:'AUR-CADENZA-S3',model_number:'AA-CS310-WN',product_family:'Cadenza Wireless',category:'Wireless Home Speakers',description:'Room-filling smart speaker with walnut-inspired trim and privacy-first microphones.',features:['Wi-Fi 6','AirPlay-compatible streaming','Room calibration','Physical microphone disconnect'],channels:['ecommerce','ce','specialty_av','furniture'],msrp:179.99,map:169.99,wholesale:90,image_url:'/assets/aurelius/cadenza-speaker.svg',additional_categories:['Smart Home Audio']},
 {brand:'Aurelius Audio',product_name:'Sonata ANC Headphones',sku:'AUR-SONATA-H4',model_number:'AA-SH420-NV',product_family:'Sonata Personal Audio',category:'Over-Ear Headphones',description:'Upscale over-ear headphones with adaptive cancellation and soft memory-foam cushions.',features:['Adaptive ANC','Spatial audio','45-hour battery','Wired passive mode'],channels:['ecommerce','ce','department','specialty_av'],msrp:249.99,map:229.99,wholesale:125,image_url:'/assets/aurelius/sonata-headphones.svg',additional_categories:['Personal Audio']},
 {brand:'Aurelius Audio',product_name:'Helios Network Streamer',sku:'AUR-HELIOS-N5',model_number:'AA-HN500-BK',product_family:'Helios Components',category:'Network Audio Players',description:'Compact network streamer that brings high-resolution playback to existing stereo systems.',features:['24-bit/192kHz streaming','Ethernet and Wi-Fi','Optical and coaxial outputs','Multi-room synchronization'],channels:['ecommerce','specialty_av','dealer'],msrp:329.99,map:299.99,wholesale:170,image_url:'/assets/aurelius/helios-streamer.svg',additional_categories:['Home Audio Components']},
 {brand:'Aurelius Audio',product_name:'Atlas Bookshelf Speakers',sku:'AUR-ATLAS-B6',model_number:'AA-AB610-WA',product_family:'Atlas Loudspeakers',category:'Bookshelf Speakers',description:'Matched pair of refined two-way bookshelf speakers with a warm walnut finish.',features:['5.25-inch woven woofer','Silk-dome tweeter','Rear bass port','Magnetic grilles'],channels:['specialty_av','dealer','ecommerce','furniture'],msrp:399.99,map:379.99,wholesale:210,image_url:'/assets/aurelius/atlas-bookshelf.svg',additional_categories:['Passive Speakers']},
 {brand:'Aurelius Audio',product_name:'Selene Wireless Subwoofer',sku:'AUR-SELENE-S8',model_number:'AA-SS800-MB',product_family:'Selene Bass',category:'Subwoofers',description:'Sealed wireless subwoofer engineered for controlled bass in music and cinema systems.',features:['8-inch long-throw driver','300W peak amplifier','Wireless and line inputs','App-based room EQ'],channels:['specialty_av','dealer','ce','ecommerce'],msrp:449.99,map:429.99,wholesale:240,image_url:'/assets/aurelius/selene-subwoofer.svg',additional_categories:['Home Theater Audio']},
 {brand:'Aurelius Audio',product_name:'Aria 3.1 Dolby Atmos Soundbar',sku:'AUR-ARIA-A7',model_number:'AA-AS730-SL',product_family:'Aria Cinema',category:'Soundbars',description:'Slim 3.1-channel soundbar with elevated dialogue clarity and immersive virtual height effects.',features:['Dolby Atmos','Dedicated center channel','HDMI eARC','Wireless subwoofer ready'],channels:['ce','ecommerce','specialty_av','department'],msrp:549.99,map:499.99,wholesale:285,image_url:'/assets/aurelius/aria-soundbar.svg',additional_categories:['Home Theater Audio']},
 {brand:'Aurelius Audio',product_name:'Elysian Integrated Amplifier',sku:'AUR-ELYSIAN-I8',model_number:'AA-EI820-BR',product_family:'Elysian Reference',category:'Integrated Amplifiers',description:'Modern integrated amplifier combining high-current analog power with premium digital inputs.',features:['100W per channel','ESS reference DAC','Moving-magnet phono stage','Balanced XLR input'],channels:['specialty_av','dealer','ecommerce'],msrp:699.99,map:649.99,wholesale:370,image_url:'/assets/aurelius/elysian-amplifier.svg',additional_categories:['Stereo Components']},
 {brand:'Aurelius Audio',product_name:'Apex Floorstanding Speaker',sku:'AUR-APEX-F9',model_number:'AA-AF900-EB',product_family:'Apex Loudspeakers',category:'Floorstanding Speakers',description:'Three-way floorstanding loudspeaker designed for wide soundstage and articulate low-frequency extension.',features:['Dual 6.5-inch woofers','Dedicated midrange driver','AMT tweeter','Adjustable isolation feet'],channels:['specialty_av','dealer','furniture'],msrp:849.99,map:799.99,wholesale:450,image_url:'/assets/aurelius/apex-floorstanding.svg',additional_categories:['Passive Speakers']},
 {brand:'Aurelius Audio',product_name:'Imperium Reference Wireless Pair',sku:'AUR-IMPERIUM-R10',model_number:'AA-IR1000-WN',product_family:'Imperium Reference',category:'Powered Stereo Speakers',description:'Flagship active stereo pair with high-resolution wireless streaming and room correction.',features:['Bi-amplified drivers','24-bit/192kHz streaming','Automated room correction','HDMI eARC and phono input'],channels:['specialty_av','dealer','ecommerce'],msrp:999.99,map:949.99,wholesale:540,image_url:'/assets/aurelius/imperium-reference.svg',additional_categories:['Wireless Home Audio']}
].map(x=>({...x,brand_website:'https://example.invalid/aurelius-audio',product_url:'',source_url:`demo://aurelius-audio/${x.sku.toLowerCase()}`,source_type:'demo',demo_data:true,positioning:'Fictional upscale audio demo product for Launchpad36 workflow evaluation.',differentiator:'Synthetic catalog data; not a real or commercially available product.'}));

export default async function handler(req,res){const tenant=await resolveTenant(req,res);if(!tenant)return;if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});res.setHeader('Cache-Control','no-store');return res.status(200).json({version:'9.8.3',status:'DEMO_REVIEW_REQUIRED',source_type:'demo',demo_data:true,fictional:true,rows:AURELIUS_AUDIO_DEMO,interpretation:'Fictional demo data only. Review and explicitly approve before importing.'})}
