import { db } from './_db.js';
import { requireInternal } from './_auth.js';
import { refreshTier } from './_living-intelligence.js';
import { normalizePublicUrl } from './_url.js';
export default async function handler(req,res){if(!requireInternal(req,res))return;const sql=db();
 try{
  if(req.method==='GET'){const rows=await sql`select mt.*,es.source_url,es.source_kind,es.last_verified_at,es.last_status from monitor_targets mt join evidence_sources es on es.id=mt.source_id order by mt.next_check_at nulls first,es.source_url`;return res.status(200).json({version:'9.8.3',monitor_targets:rows,credentials_configured:Boolean(process.env.FIRECRAWL_API_KEY),webhook_configured:Boolean(process.env.FIRECRAWL_MONITOR_WEBHOOK_URL&&process.env.FIRECRAWL_WEBHOOK_SECRET)})}
  if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
  const sourceUrl=normalizePublicUrl(req.body?.source_url),targetType=String(req.body?.target_type||'retailer_assortment').trim(),tier=refreshTier(req.body?.refresh_tier),accountId=req.body?.account_id||null,organizationId=req.body?.organization_id||null,replaceTargetId=String(req.body?.replace_target_id||'').trim(),categoryFocus=String(req.body?.category_focus||'').replace(/\s+/g,' ').trim().slice(0,160);if(!sourceUrl)return res.status(400).json({error:'Valid public source_url is required'});if(targetType==='retailer_assortment'&&!categoryFocus)return res.status(400).json({error:'Category is required for retailer assortment targets'});if(replaceTargetId){if(!/^[0-9a-f-]{36}$/i.test(replaceTargetId))return res.status(400).json({error:'Valid replace_target_id is required'});const replaced=await sql`update monitor_targets set state='inactive',updated_at=now() where id=${replaceTargetId} and state='active' returning id`;if(!replaced[0])return res.status(404).json({error:'Active monitoring target to replace was not found'})}
  if(accountId&&!(await sql`select id from accounts where id=${accountId} limit 1`)[0])return res.status(400).json({error:'account_id does not exist'});if(organizationId&&!(await sql`select id from retail_organizations where id=${organizationId} limit 1`)[0])return res.status(400).json({error:'organization_id does not exist'});
  const host=new URL(sourceUrl).hostname.replace(/^www\./,'');const source=(await sql`insert into evidence_sources(source_url,source_kind,publisher,domain,refresh_tier,last_status,updated_at) values(${sourceUrl},${targetType},${req.body?.publisher||''},${host},${tier},'MONITOR_PENDING',now()) on conflict(source_url) do update set source_kind=excluded.source_kind,refresh_tier=excluded.refresh_tier,updated_at=now() returning *`)[0];
  const target=(await sql`insert into monitor_targets(source_id,account_id,organization_id,target_type,category_focus,refresh_tier,provider,provider_monitor_id,state,next_check_at,updated_at) values(${source.id},${accountId},${organizationId},${targetType},${categoryFocus},${tier},'firecrawl',${req.body?.provider_monitor_id||''},'active',now(),now()) on conflict(source_id,target_type) do update set account_id=excluded.account_id,organization_id=excluded.organization_id,category_focus=excluded.category_focus,refresh_tier=excluded.refresh_tier,provider_monitor_id=case when excluded.provider_monitor_id<>'' then excluded.provider_monitor_id else monitor_targets.provider_monitor_id end,state='active',updated_at=now() returning *`)[0];
  return res.status(200).json({version:'9.8.3',status:target.provider_monitor_id?'MONITOR_LINKED':'PROVIDER_PROVISIONING_REQUIRED',target,source,firecrawl:{mode:'page',schedule:tier,webhook_url_env:'FIRECRAWL_MONITOR_WEBHOOK_URL',webhook_events:['monitor.page','monitor.check.completed'],credentials_env:'FIRECRAWL_API_KEY',webhook_authentication:'X-Firecrawl-Signature HMAC-SHA256 using FIRECRAWL_WEBHOOK_SECRET'},interpretation:'The local target is saved. Configure the Firecrawl account webhook secret, then provision the page monitor and update this target with its provider monitor ID.'});
 }catch(e){return res.status(500).json({error:e.message})}}
