import { db } from './_db.js';
import { resolveTenant } from './_tenant.js';
import { ensureIdentitySchema, hashPassword, isPermanentAdminEmail, normalizeRole } from './_identity.js';
import { appendPermissionAudit } from './_permission-audit.js';
import { CAPABILITIES, ROLES, canonicalRole, hasCapability, managerMayGrant, permissionSummary, teamScopeIncludes } from './_permissions.js';

const clean=(value,max=240)=>String(value??'').trim().slice(0,max);
async function activity(sql,tenant,userId,action,subjectType,subjectId,metadata={}){await sql`insert into tenant_activity_log(manufacturer_id,user_id,action,subject_type,subject_id,metadata) values(${tenant.tenant_id},${userId||null},${action},${subjectType},${String(subjectId||'')},${sql.json(metadata)})`}
async function targetTeamIds(sql,tenantId,memberId){return (await sql`select mtm.team_id from manufacturer_team_members mtm join manufacturer_teams t on t.id=mtm.team_id where mtm.member_id=${memberId} and t.manufacturer_id=${tenantId} and t.active=true`).map(row=>String(row.team_id))}
async function member(sql,tenantId,memberId){return (await sql`select id,email,display_name,role,active,default_team_id from manufacturer_members where id=${memberId} and manufacturer_id=${tenantId} limit 1`)[0]}
async function team(sql,tenantId,teamId){return teamId?(await sql`select id,name,active from manufacturer_teams where id=${teamId} and manufacturer_id=${tenantId} limit 1`)[0]:null}
function teamAllowed(tenant,teamId){return hasCapability(tenant,CAPABILITIES.USER_ADMIN_TENANT)||(hasCapability(tenant,CAPABILITIES.USER_ADMIN_TEAM)&&(tenant.team_ids||[]).includes(String(teamId)))}
function grantAllowed(tenant,role){return hasCapability(tenant,CAPABILITIES.USER_ADMIN_TENANT)||managerMayGrant(role)}

export default async function handler(req,res){
 const tenant=await resolveTenant(req,res,{enforceWriteCapability:false});if(!tenant)return;
 const sql=db(),actorId=tenant.user_id||null,isTenantAdmin=hasCapability(tenant,CAPABILITIES.USER_ADMIN_TENANT);let actor=null,action=clean(req.body?.action,40).toLowerCase()||String(req.method||'GET').toUpperCase();
 const audit=details=>appendPermissionAudit({sql,req,tenant,actor,action_type:action.toUpperCase(),...details});
 try{
  await ensureIdentitySchema(sql);actor=actorId?await member(sql,tenant.tenant_id,actorId):{id:null,display_name:'Platform Admin',role:'ADMIN'};
  if(!isTenantAdmin&&!hasCapability(tenant,CAPABILITIES.USER_ADMIN_TEAM)){await audit({result:'DENIED',reason:'Role has no user administration capability'});return res.status(403).json({error:'User administration permission is required',code:'FORBIDDEN'})}
  if(req.method==='GET'){
   const [members,teams,memberships]=isTenantAdmin?await Promise.all([
    sql`select id,email,display_name,role,active,default_team_id,last_login_at,created_at from manufacturer_members where manufacturer_id=${tenant.tenant_id} order by active desc,display_name,email`,
    sql`select * from manufacturer_teams where manufacturer_id=${tenant.tenant_id} order by active desc,name`,
    sql`select mtm.team_id,mtm.member_id,mtm.role from manufacturer_team_members mtm join manufacturer_teams t on t.id=mtm.team_id where t.manufacturer_id=${tenant.tenant_id}`
   ]):await Promise.all([
    sql`select distinct mm.id,mm.email,mm.display_name,mm.role,mm.active,mm.default_team_id,mm.last_login_at,mm.created_at from manufacturer_members mm join manufacturer_team_members mtm on mtm.member_id=mm.id where mm.manufacturer_id=${tenant.tenant_id} and mtm.team_id=any(${tenant.team_ids}::uuid[]) order by mm.active desc,mm.display_name,mm.email`,
    sql`select * from manufacturer_teams where manufacturer_id=${tenant.tenant_id} and id=any(${tenant.team_ids}::uuid[]) and active=true order by name`,
    sql`select mtm.team_id,mtm.member_id,mtm.role from manufacturer_team_members mtm join manufacturer_teams t on t.id=mtm.team_id where t.manufacturer_id=${tenant.tenant_id} and mtm.team_id=any(${tenant.team_ids}::uuid[])`
   ]);
   return res.status(200).json({members:members.map(item=>({...item,role:canonicalRole(item.role)})),teams,memberships,permissions:permissionSummary(tenant)});
  }
  if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
  if(action==='create_team'){
   const name=clean(req.body?.name,160);if(!isTenantAdmin){await audit({result:'DENIED',new_value:{team_name:name},reason:'Only Administrators can create teams'});return res.status(403).json({error:'Only Administrators can create teams'})}if(!name){await audit({result:'FAILED',reason:'Team name is required'});return res.status(400).json({error:'Team name is required'})}
   const row=(await sql`insert into manufacturer_teams(manufacturer_id,name,description) values(${tenant.tenant_id},${name},${clean(req.body?.description,500)}) on conflict(manufacturer_id,lower(name)) do update set active=true,description=excluded.description,updated_at=now() returning *`)[0];await activity(sql,tenant,actorId,'TEAM_CREATED','team',row.id,{name:row.name});await audit({target_team:row,new_value:{name:row.name,active:row.active},result:'SUCCESS'});return res.status(201).json({team:row});
  }
  if(action==='create_user'){
   const email=clean(req.body?.email).toLowerCase(),displayName=clean(req.body?.display_name,180),role=isPermanentAdminEmail(email)?ROLES.ADMIN:normalizeRole(req.body?.role),password=String(req.body?.password||''),teamId=clean(req.body?.team_id,80)||null,targetTeam=await team(sql,tenant.tenant_id,teamId),attempted={email,display_name:displayName,role,team_id:teamId};
   if(!email||!email.includes('@')){await audit({new_value:attempted,result:'FAILED',reason:'Valid email is required'});return res.status(400).json({error:'Valid email is required'})}
   if(!teamId&&!isTenantAdmin){await audit({target_user:{email,display_name:displayName},new_value:attempted,result:'DENIED',reason:'Managers must create users inside an authorized team'});return res.status(403).json({error:'Managers must create users inside one of their teams'})}
   if(teamId&&(!targetTeam||!teamAllowed(tenant,teamId))){await audit({target_user:{email,display_name:displayName},target_team:targetTeam||{},new_value:attempted,result:'DENIED',reason:'Actor cannot administer the requested team'});return res.status(403).json({error:'You cannot administer that team'})}
   if(!grantAllowed(tenant,role)){await audit({target_user:{email,display_name:displayName},target_team:targetTeam,new_value:attempted,result:'DENIED',reason:`Manager cannot grant ${role}`});return res.status(403).json({error:'You cannot grant that role'})}
   const existing=(await sql`select id,email,display_name,role,active from manufacturer_members where manufacturer_id=${tenant.tenant_id} and lower(email)=${email} limit 1`)[0];if(existing&&!isTenantAdmin&&!teamScopeIncludes(tenant.team_ids,await targetTeamIds(sql,tenant.tenant_id,existing.id))){await audit({target_user:existing,target_team:targetTeam,new_value:attempted,result:'DENIED',reason:'Manager attempted to update a user outside authorized teams'});return res.status(403).json({error:'You cannot update a user outside your teams'})}
   let passwordHash;try{passwordHash=hashPassword(password)}catch(error){await audit({target_user:existing||{email,display_name:displayName},target_team:targetTeam,new_value:attempted,result:'FAILED',reason:error.message});throw error}
   const created=(await sql`insert into manufacturer_members(manufacturer_id,email,display_name,role,active,password_hash,default_team_id,created_by,updated_at) values(${tenant.tenant_id},${email},${displayName},${role},true,${passwordHash},${teamId},${actorId},now()) on conflict(manufacturer_id,lower(email)) do update set display_name=excluded.display_name,role=excluded.role,active=true,password_hash=excluded.password_hash,default_team_id=coalesce(excluded.default_team_id,manufacturer_members.default_team_id),updated_at=now() returning *`)[0];if(teamId)await sql`insert into manufacturer_team_members(team_id,member_id,role) values(${teamId},${created.id},'member') on conflict(team_id,member_id) do update set role=excluded.role`;await activity(sql,tenant,actorId,'USER_CREATED','user',created.id,{email:created.email,role:canonicalRole(created.role),team_id:teamId});await audit({target_user:created,target_team:targetTeam,previous_value:existing?{role:canonicalRole(existing.role),active:existing.active}:{},new_value:{role:canonicalRole(created.role),active:true,team_id:teamId},result:'SUCCESS'});return res.status(201).json({member:{id:created.id,email:created.email,display_name:created.display_name,role:canonicalRole(created.role),default_team_id:created.default_team_id}});
  }
  const memberId=clean(req.body?.member_id,80),requestedTarget=await member(sql,tenant.tenant_id,memberId),authorized=isTenantAdmin||(requestedTarget&&String(memberId)!==String(actorId)&&canonicalRole(requestedTarget.role)!==ROLES.ADMIN&&teamScopeIncludes(tenant.team_ids,await targetTeamIds(sql,tenant.tenant_id,memberId)));
  if(!requestedTarget||!authorized){await audit({target_user:requestedTarget||{},new_value:{requested_action:action,requested_target_id:memberId},result:'DENIED',reason:requestedTarget?'Manager attempted cross-team or privileged-user administration':'Target user is outside this tenant'});return res.status(403).json({error:'You cannot administer this user'})}
  if(action==='reset_password'){let hash;try{hash=hashPassword(String(req.body?.password||''))}catch(error){await audit({target_user:requestedTarget,result:'FAILED',reason:error.message});throw error}await sql`update manufacturer_members set password_hash=${hash},active=true,updated_at=now() where id=${memberId}`;await activity(sql,tenant,actorId,'USER_PASSWORD_RESET','user',memberId,{email:requestedTarget.email});await audit({target_user:requestedTarget,previous_value:{active:requestedTarget.active},new_value:{active:true,password_reset:true},result:'SUCCESS'});return res.status(200).json({reset:true,member_id:memberId})}
  if(action==='set_role'){const role=normalizeRole(req.body?.role);if(isPermanentAdminEmail(requestedTarget.email)&&role!==ROLES.ADMIN){await audit({target_user:requestedTarget,previous_value:{role:canonicalRole(requestedTarget.role)},new_value:{role},result:'DENIED',reason:'Permanent Administrator cannot be downgraded'});return res.status(400).json({error:'This account is a permanent workspace administrator'})}if(!grantAllowed(tenant,role)){await audit({target_user:requestedTarget,previous_value:{role:canonicalRole(requestedTarget.role)},new_value:{role},result:'DENIED',reason:`Manager cannot grant ${role}`});return res.status(403).json({error:'You cannot grant that role'})}const row=(await sql`update manufacturer_members set role=${role},updated_at=now() where id=${memberId} returning id,email,display_name,role`)[0];await activity(sql,tenant,actorId,'USER_ROLE_CHANGED','user',memberId,{from:canonicalRole(requestedTarget.role),to:canonicalRole(role)});await audit({target_user:row,previous_value:{role:canonicalRole(requestedTarget.role)},new_value:{role:canonicalRole(role)},result:'SUCCESS'});return res.status(200).json({member:{...row,role:canonicalRole(row.role)}})}
  if(action==='assign_team'||action==='remove_team'){const teamId=clean(req.body?.team_id,80),targetTeam=await team(sql,tenant.tenant_id,teamId);if(!targetTeam||!teamAllowed(tenant,teamId)){await audit({target_user:requestedTarget,target_team:targetTeam||{},new_value:{requested_team_id:teamId},result:'DENIED',reason:'Actor cannot administer the requested team'});return res.status(403).json({error:'You cannot administer that team'})}const assigned=(await sql`select 1 from manufacturer_team_members where team_id=${teamId} and member_id=${memberId} limit 1`).length>0;if(action==='assign_team')await sql`insert into manufacturer_team_members(team_id,member_id,role) values(${teamId},${memberId},'member') on conflict(team_id,member_id) do update set role='member'`;else await sql`delete from manufacturer_team_members where team_id=${teamId} and member_id=${memberId}`;await activity(sql,tenant,actorId,action==='assign_team'?'TEAM_ASSIGNED':'TEAM_REMOVED','user',memberId,{team_id:teamId});await audit({target_user:requestedTarget,target_team:targetTeam,previous_value:{assigned},new_value:{assigned:action==='assign_team'},result:'SUCCESS'});return res.status(200).json({assigned:action==='assign_team'})}
  if(action==='set_active'){const active=req.body?.active===true;if(String(actorId)===memberId&&!active){await audit({target_user:requestedTarget,previous_value:{active:requestedTarget.active},new_value:{active},result:'DENIED',reason:'User cannot deactivate own account'});return res.status(400).json({error:'You cannot deactivate your own account'})}const row=(await sql`update manufacturer_members set active=${active},updated_at=now() where id=${memberId} returning id,active`)[0];await activity(sql,tenant,actorId,active?'USER_ACTIVATED':'USER_DEACTIVATED','user',memberId,{});await audit({target_user:requestedTarget,previous_value:{active:requestedTarget.active},new_value:{active},result:'SUCCESS'});return res.status(200).json({member:row})}
  await audit({target_user:requestedTarget,new_value:{requested_action:action},result:'FAILED',reason:'Unsupported action'});return res.status(400).json({error:'Unsupported action'});
 }catch(error){if(actor)try{await audit({result:'FAILED',reason:'User administration operation failed'})}catch{}console.error('team admin failed',{message:error?.message||String(error)});return res.status(error.status||500).json({error:error.message||'User administration operation failed'})}
}
